### ISSUE TITLE
Shortcut TimeSetup

### ISSUE THREAD

**Issue by Emil3005** [Bartoldus-Studio/RTSRevival#21]
Add the shortcut to fasten or slow the time using the + and - buttons

**Comment by Justus3007** [comment]
Added in 894147efa215b0e0ef2d3e8072fb7725d8918618
However UE5 does not know the Button "-" next to the right shift key or i didnt find the correct name for it
It wasnt "underscore"

so Button "+" on numpad and next to enter makes the time faster and "Num - " slowes the time down
